"""Update MatchedTransaction with all Cashbook headers

Revision ID: 12dd40e6c75e
Revises: efc249b46492
Create Date: 2025-10-27 23:43:04.475514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12dd40e6c75e'
down_revision = 'efc249b46492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matched_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_client_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_amount', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('stripe_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('billing_entity', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ar_account', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('account', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('transtype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('card_reference', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reasoncode', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sepaprovider', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('invoice_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('memo', sa.Float(), nullable=True))
        batch_op.alter_column('client_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('client_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matched_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('memo')
        batch_op.drop_column('payment_hash')
        batch_op.drop_column('invoice_hash')
        batch_op.drop_column('sepaprovider')
        batch_op.drop_column('reasoncode')
        batch_op.drop_column('card_reference')
        batch_op.drop_column('comment')
        batch_op.drop_column('transtype')
        batch_op.drop_column('location')
        batch_op.drop_column('account')
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('currency')
        batch_op.drop_column('ar_account')
        batch_op.drop_column('billing_entity')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('stripe_date')
        batch_op.drop_column('stripe_amount')
        batch_op.drop_column('stripe_client_number')

    # ### end Alembic commands ###
