"""Add all columns from both files to MatchedTransaction

Revision ID: 13be584eb93e
Revises: d5c14a7b5f94
Create Date: 2025-10-28 01:53:23.216373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13be584eb93e'
down_revision = 'd5c14a7b5f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matched_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cb_payment_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cb_client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cb_invoice_number', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cb_billing_entity', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cb_ar_account', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cb_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('cb_exchange_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cb_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cb_account', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cb_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cb_transtype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cb_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cb_card_reference', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cb_reasoncode', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cb_sepaprovider', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cb_invoice_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cb_payment_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cb_memo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stripe_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_stripe_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_created', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stripe_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('stripe_converted_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stripe_fees', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stripe_net', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stripe_converted_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('stripe_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_purpose_metadata', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_phorest_client_id_metadata', sa.String(length=255), nullable=True))
        batch_op.alter_column('stripe_client_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('stripe_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('stripe_date')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('client_id')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('reasoncode')
        batch_op.drop_column('currency')
        batch_op.drop_column('sepaprovider')
        batch_op.drop_column('comment')
        batch_op.drop_column('transtype')
        batch_op.drop_column('ar_account')
        batch_op.drop_column('memo')
        batch_op.drop_column('invoice_hash')
        batch_op.drop_column('amount')
        batch_op.drop_column('location')
        batch_op.drop_column('billing_entity')
        batch_op.drop_column('card_reference')
        batch_op.drop_column('payment_hash')
        batch_op.drop_column('account')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matched_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('card_reference', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('billing_entity', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('memo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ar_account', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transtype', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sepaprovider', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reasoncode', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stripe_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('stripe_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
        batch_op.alter_column('stripe_client_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('stripe_phorest_client_id_metadata')
        batch_op.drop_column('stripe_purpose_metadata')
        batch_op.drop_column('stripe_customer_name')
        batch_op.drop_column('stripe_customer_email')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('stripe_details')
        batch_op.drop_column('stripe_converted_currency')
        batch_op.drop_column('stripe_net')
        batch_op.drop_column('stripe_fees')
        batch_op.drop_column('stripe_converted_amount')
        batch_op.drop_column('stripe_currency')
        batch_op.drop_column('stripe_description')
        batch_op.drop_column('stripe_created')
        batch_op.drop_column('stripe_stripe_id')
        batch_op.drop_column('stripe_type')
        batch_op.drop_column('cb_memo')
        batch_op.drop_column('cb_payment_hash')
        batch_op.drop_column('cb_invoice_hash')
        batch_op.drop_column('cb_sepaprovider')
        batch_op.drop_column('cb_reasoncode')
        batch_op.drop_column('cb_card_reference')
        batch_op.drop_column('cb_comment')
        batch_op.drop_column('cb_transtype')
        batch_op.drop_column('cb_location')
        batch_op.drop_column('cb_account')
        batch_op.drop_column('cb_amount')
        batch_op.drop_column('cb_exchange_rate')
        batch_op.drop_column('cb_currency')
        batch_op.drop_column('cb_ar_account')
        batch_op.drop_column('cb_billing_entity')
        batch_op.drop_column('cb_invoice_number')
        batch_op.drop_column('cb_client_id')
        batch_op.drop_column('cb_payment_date')

    # ### end Alembic commands ###
