"""Add CashbookTransaction model

Revision ID: 43fe7f7060a7
Revises: 8c3892b032b9
Create Date: 2025-10-27 19:43:42.823301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43fe7f7060a7'
down_revision = '8c3892b032b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashbook_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subsidiary_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('billing_entity', sa.String(length=500), nullable=True),
    sa.Column('ar_account', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('account', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('transtype', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('card_reference', sa.Float(), nullable=True),
    sa.Column('reasoncode', sa.Float(), nullable=True),
    sa.Column('sepaprovider', sa.String(length=255), nullable=True),
    sa.Column('invoice_hash', sa.String(length=255), nullable=True),
    sa.Column('payment_hash', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashbook_transactions')
    # ### end Alembic commands ###
