"""Add description_client_id to StripeTransaction

Revision ID: 6e21b2dc9ec6
Revises: 13be584eb93e
Create Date: 2025-10-28 13:39:49.688330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e21b2dc9ec6'
down_revision = '13be584eb93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_client_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_transactions', schema=None) as batch_op:
        batch_op.drop_column('description_client_id')

    # ### end Alembic commands ###
