"""Add StripeTransaction model

Revision ID: 8c3892b032b9
Revises: a28056ecb077
Create Date: 2025-10-27 19:25:11.359033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3892b032b9'
down_revision = 'a28056ecb077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subsidiary_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('client_number', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('stripe_id', sa.String(length=255), nullable=True),
    sa.Column('created', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('converted_amount', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('net', sa.Float(), nullable=True),
    sa.Column('converted_currency', sa.String(length=10), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('purpose_metadata', sa.String(length=255), nullable=True),
    sa.Column('phorest_client_id_metadata', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_transactions')
    # ### end Alembic commands ###
