"""Add JournalTransaction table for one-way journal sync

Revision ID: 8d1ea009db82
Revises: 6e21b2dc9ec6
Create Date: 2025-10-28 22:36:56.034639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1ea009db82'
down_revision = '6e21b2dc9ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('subsidiary_id', sa.Integer(), nullable=False),
    sa.Column('matched_transaction_id', sa.Integer(), nullable=False),
    sa.Column('journal_type', sa.String(length=50), nullable=True),
    sa.Column('journal_memo', sa.String(length=500), nullable=True),
    sa.Column('journal_invoice_number', sa.String(length=255), nullable=True),
    sa.Column('journal_payment_number', sa.String(length=255), nullable=True),
    sa.Column('cb_payment_date', sa.String(length=20), nullable=True),
    sa.Column('cb_client_id', sa.Integer(), nullable=True),
    sa.Column('cb_invoice_number', sa.String(length=255), nullable=True),
    sa.Column('cb_billing_entity', sa.String(length=500), nullable=True),
    sa.Column('cb_ar_account', sa.String(length=500), nullable=True),
    sa.Column('cb_currency', sa.String(length=10), nullable=True),
    sa.Column('cb_exchange_rate', sa.Float(), nullable=True),
    sa.Column('cb_amount', sa.Float(), nullable=True),
    sa.Column('cb_account', sa.String(length=500), nullable=True),
    sa.Column('cb_location', sa.String(length=100), nullable=True),
    sa.Column('cb_transtype', sa.String(length=100), nullable=True),
    sa.Column('cb_comment', sa.Text(), nullable=True),
    sa.Column('cb_card_reference', sa.Float(), nullable=True),
    sa.Column('cb_reasoncode', sa.Float(), nullable=True),
    sa.Column('cb_sepaprovider', sa.String(length=255), nullable=True),
    sa.Column('cb_invoice_hash', sa.String(length=255), nullable=True),
    sa.Column('cb_payment_hash', sa.String(length=255), nullable=True),
    sa.Column('cb_memo', sa.Float(), nullable=True),
    sa.Column('stripe_client_number', sa.String(length=50), nullable=True),
    sa.Column('stripe_type', sa.String(length=100), nullable=True),
    sa.Column('stripe_stripe_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_created', sa.String(length=100), nullable=True),
    sa.Column('stripe_description', sa.Text(), nullable=True),
    sa.Column('stripe_amount', sa.Float(), nullable=True),
    sa.Column('stripe_currency', sa.String(length=10), nullable=True),
    sa.Column('stripe_converted_amount', sa.Float(), nullable=True),
    sa.Column('stripe_fees', sa.Float(), nullable=True),
    sa.Column('stripe_net', sa.Float(), nullable=True),
    sa.Column('stripe_converted_currency', sa.String(length=10), nullable=True),
    sa.Column('stripe_details', sa.Text(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_email', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_name', sa.String(length=255), nullable=True),
    sa.Column('stripe_purpose_metadata', sa.String(length=255), nullable=True),
    sa.Column('stripe_phorest_client_id_metadata', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_transactions')
    # ### end Alembic commands ###
