"""Change CashbookTransaction payment_date to string format

Revision ID: bca09594dd0e
Revises: c9571a077d6e
Create Date: 2025-10-27 22:20:56.031223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bca09594dd0e'
down_revision = 'c9571a077d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashbook_transactions', schema=None) as batch_op:
        batch_op.alter_column('payment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashbook_transactions', schema=None) as batch_op:
        batch_op.alter_column('payment_date',
               existing_type=sa.String(length=20),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
