"""Change payment_date to string format dd/mm/yyyy

Revision ID: c9571a077d6e
Revises: b30d163f4887
Create Date: 2025-10-27 21:54:31.729756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9571a077d6e'
down_revision = 'b30d163f4887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('looker_cashbook_transactions', schema=None) as batch_op:
        batch_op.alter_column('payment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('looker_cashbook_transactions', schema=None) as batch_op:
        batch_op.alter_column('payment_date',
               existing_type=sa.String(length=20),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
