"""Add ReconciliationResults table for persistent metadata

Revision ID: d5c14a7b5f94
Revises: ffa52d094c98
Create Date: 2025-10-27 23:53:33.209703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c14a7b5f94'
down_revision = 'ffa52d094c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('subsidiary_id', sa.Integer(), nullable=False),
    sa.Column('process_number', sa.Integer(), nullable=False),
    sa.Column('cutoff_date', sa.String(length=20), nullable=True),
    sa.Column('unmatched_stripe_count', sa.Integer(), nullable=True),
    sa.Column('unmatched_cashbook_count', sa.Integer(), nullable=True),
    sa.Column('out_of_cutoff_count', sa.Integer(), nullable=True),
    sa.Column('multiple_matches_count', sa.Integer(), nullable=True),
    sa.Column('unmatched_stripe_p2_count', sa.Integer(), nullable=True),
    sa.Column('unmatched_cashbook_p2_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliation_results')
    # ### end Alembic commands ###
