"""Add MatchedTransaction model

Revision ID: efc249b46492
Revises: bca09594dd0e
Create Date: 2025-10-27 23:37:34.145316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc249b46492'
down_revision = 'bca09594dd0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matched_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('subsidiary_id', sa.Integer(), nullable=False),
    sa.Column('stripe_id', sa.Integer(), nullable=False),
    sa.Column('cashbook_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('process_number', sa.Integer(), nullable=False),
    sa.Column('client_number', sa.String(length=100), nullable=True),
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matched_transactions')
    # ### end Alembic commands ###
