"""Create MatchedTransaction table with all Cashbook headers

Revision ID: ffa52d094c98
Revises: 12dd40e6c75e
Create Date: 2025-10-27 23:43:29.862999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa52d094c98'
down_revision = '12dd40e6c75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matched_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('subsidiary_id', sa.Integer(), nullable=False),
    sa.Column('stripe_id', sa.Integer(), nullable=False),
    sa.Column('stripe_client_number', sa.String(length=100), nullable=True),
    sa.Column('stripe_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('stripe_date', sa.String(length=20), nullable=True),
    sa.Column('cashbook_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.String(length=20), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('billing_entity', sa.String(length=500), nullable=True),
    sa.Column('ar_account', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('account', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('transtype', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('card_reference', sa.Float(), nullable=True),
    sa.Column('reasoncode', sa.Float(), nullable=True),
    sa.Column('sepaprovider', sa.String(length=255), nullable=True),
    sa.Column('invoice_hash', sa.String(length=255), nullable=True),
    sa.Column('payment_hash', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.Float(), nullable=True),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('process_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matched_transactions')
    # ### end Alembic commands ###
